# Form implementation generated from reading ui file 'view\login\dangky.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 355)
        MainWindow.setStyleSheet("""
            QWidget {
                background-color: #f5f5f5;
                font-family: Arial, sans-serif;
            }
            QLabel {
                color: #333;
            }
            QLineEdit {
                border: 1px solid #ccc;
                border-radius: 5px;
                padding: 5px;
                background-color: #fff;
            }
            QPushButton {
                background-color: #007bff;
                color: #fff;
                border: none;
                border-radius: 5px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #0056b3;
            }
        """)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 1, 1, 1, 1)
        self.password2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password2.setObjectName("password2")
        self.gridLayout.addWidget(self.password2, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 2)
        self.id_nv = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id_nv.setText("")
        self.id_nv.setObjectName("id_nv")
        self.gridLayout_2.addWidget(self.id_nv, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email.setObjectName("email")
        self.gridLayout_2.addWidget(self.email, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 3, 1, 1)
        self.diachi = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.diachi.setObjectName("diachi")
        self.gridLayout_2.addWidget(self.diachi, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 3, 1, 1)
        self.chucvu = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.chucvu.setObjectName("chucvu")
        self.gridLayout_2.addWidget(self.chucvu, 2, 4, 1, 1)
        self.name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        self.sdt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sdt.setObjectName("sdt")
        self.gridLayout_2.addWidget(self.sdt, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.dangky_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dangky_btn.setObjectName("dangky_btn")
        self.gridLayout_3.addWidget(self.dangky_btn, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Tên đăng nhập"))
        self.label_9.setText(_translate("MainWindow", "Xác nhận mật khẩu"))
        self.label_8.setText(_translate("MainWindow", "Mật khẩu"))
        self.label_10.setText(_translate("MainWindow", "ID tài khoản"))
        self.label_7.setText(_translate("MainWindow", "Mã NV"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.label_4.setText(_translate("MainWindow", "Địa chỉ"))
        self.label_5.setText(_translate("MainWindow", "Chức vụ"))
        self.label.setText(_translate("MainWindow", "Tên"))
        self.label_3.setText(_translate("MainWindow", "SĐT"))
        self.dangky_btn.setText(_translate("MainWindow", "Đăng ký"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
