# Form implementation generated from reading ui file 'C:\Code\DoAnPython\view\phong_va_giaphong\phong_giaphong.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(755, 603)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.phongBtn = QtWidgets.QPushButton(parent=Form)
        self.phongBtn.setObjectName("phongBtn")
        self.gridLayout.addWidget(self.phongBtn, 0, 0, 1, 1)
        self.giaphongBtn = QtWidgets.QPushButton(parent=Form)
        self.giaphongBtn.setObjectName("giaphongBtn")
        self.gridLayout.addWidget(self.giaphongBtn, 0, 1, 1, 1)
        self.phong_giaphong = QtWidgets.QStackedWidget(parent=Form)
        self.phong_giaphong.setObjectName("phong_giaphong")
        self.phong_page = QtWidgets.QWidget()
        self.phong_page.setObjectName("phong_page")
        self.phong_giaphong.addWidget(self.phong_page)
        self.giaphong_page = QtWidgets.QWidget()
        self.giaphong_page.setObjectName("giaphong_page")
        self.phong_giaphong.addWidget(self.giaphong_page)
        self.gridLayout.addWidget(self.phong_giaphong, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.phongBtn.setText(_translate("Form", "Phòng"))
        self.giaphongBtn.setText(_translate("Form", "Giá phòng"))
