from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 540)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.in_sea = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_sea.setFont(font)
        self.in_sea.setObjectName("in_sea")
        self.horizontalLayout.addWidget(self.in_sea)
        self.sea_btn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sea_btn.setFont(font)
        self.sea_btn.setObjectName("sea_btn")
        self.horizontalLayout.addWidget(self.sea_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.in_name = QtWidgets.QLineEdit(parent=Form)
        self.in_name.setObjectName("in_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.in_name)
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.in_day = QtWidgets.QLineEdit(parent=Form)
        self.in_day.setObjectName("in_day")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.in_day)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.in_hour = QtWidgets.QLineEdit(parent=Form)
        self.in_hour.setObjectName("in_hour")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.in_hour)
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.in_night = QtWidgets.QLineEdit(parent=Form)
        self.in_night.setObjectName("in_night")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.in_night)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ins_btn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ins_btn.setFont(font)
        self.ins_btn.setObjectName("ins_btn")
        self.horizontalLayout_2.addWidget(self.ins_btn)
        self.del_btn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.del_btn.setFont(font)
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_2.addWidget(self.del_btn)
        self.edi_btn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edi_btn.setFont(font)
        self.edi_btn.setObjectName("edi_btn")
        self.horizontalLayout_2.addWidget(self.edi_btn)
        self.sho_btn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sho_btn.setFont(font)
        self.sho_btn.setObjectName("sho_btn")
        self.horizontalLayout_2.addWidget(self.sho_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.dis_pla = QtWidgets.QTableWidget(parent=Form)
        self.dis_pla.setColumnCount(5)
        self.dis_pla.setObjectName("dis_pla")
        self.dis_pla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.dis_pla)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID"))
        self.sea_btn.setText(_translate("Form", "Tìm kiếm"))
        self.label_3.setText(_translate("Form", "Tên (loại)"))
        self.label_5.setText(_translate("Form", "Ngày"))
        self.label_4.setText(_translate("Form", "Giờ"))
        self.label_6.setText(_translate("Form", "Đêm"))
        self.ins_btn.setText(_translate("Form", "Thêm"))
        self.del_btn.setText(_translate("Form", "Xóa"))
        self.edi_btn.setText(_translate("Form", "Sửa"))
        self.sho_btn.setText(_translate("Form", " Hiển thị"))
        item = self.dis_pla.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.dis_pla.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên (loại)"))
        item = self.dis_pla.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Giờ"))
        item = self.dis_pla.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Ngày"))
        item = self.dis_pla.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Đêm"))
