# Form implementation generated from reading ui file 'view/khach_hang/kh_form.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_khform(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 609)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.customer = QtWidgets.QWidget()
        self.customer.setObjectName("customer")
        self.stackedWidget.addWidget(self.customer)
        self.find_face = QtWidgets.QWidget()
        self.find_face.setObjectName("find_face")
        self.stackedWidget.addWidget(self.find_face)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
