# Form implementation generated from reading ui file 'view\khach_hang\kh_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QButtonGroup

class Ui_CustomerManagement(object):
    def setupUi(self, CustomerManagement):
        CustomerManagement.setObjectName("CustomerManagement")
        CustomerManagement.resize(992, 384)
        CustomerManagement.setStyleSheet("""
            QWidget {
                background-color: #f5f5f5;
                font-family: Arial, sans-serif;
            }
            QLabel {
                color: #333;
            }
            QLineEdit {
                border: 1px solid #ccc;
                border-radius: 5px;
                padding: 5px;
                background-color: #fff;
            }
            QPushButton {
                background-color: #007bff;
                color: #fff;
                border: none;
                border-radius: 5px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #0056b3;
            }
            QTableView {
                border: 1px solid #ccc;
                background-color: #fff;
            }
            QHeaderView::section {
                background-color: #007bff;
                color: #fff;
                padding: 5px;
                border: none;
            }
        """)
        self.mainLayout = QtWidgets.QHBoxLayout(CustomerManagement)
        self.mainLayout.setObjectName("mainLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.searchLabel = QtWidgets.QLabel(parent=CustomerManagement)
        self.searchLabel.setObjectName("searchLabel")
        self.searchLayout.addWidget(self.searchLabel)
        self.searchLineEdit = QtWidgets.QLineEdit(parent=CustomerManagement)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchLayout.addWidget(self.searchLineEdit)
        self.searchButton = QtWidgets.QPushButton(parent=CustomerManagement)
        self.searchButton.setObjectName("searchButton")
        self.searchLayout.addWidget(self.searchButton)
        self.verticalLayout_3.addLayout(self.searchLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=CustomerManagement)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.nameLineEdit = QtWidgets.QLineEdit(parent=CustomerManagement)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameLineEdit)
        self.label_3 = QtWidgets.QLabel(parent=CustomerManagement)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.phoneLineEdit = QtWidgets.QLineEdit(parent=CustomerManagement)
        self.phoneLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.phoneLineEdit.setObjectName("phoneLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phoneLineEdit)
        self.label_4 = QtWidgets.QLabel(parent=CustomerManagement)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.widget = QtWidgets.QWidget(parent=CustomerManagement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageButton = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageButton.sizePolicy().hasHeightForWidth())
        self.imageButton.setSizePolicy(sizePolicy)
        self.imageButton.setMinimumSize(QtCore.QSize(40, 0))
        self.imageButton.setObjectName("imageButton")
        self.horizontalLayout_2.addWidget(self.imageButton)
        self.label_imagePath = QtWidgets.QLabel(parent=self.widget)
        self.label_imagePath.setText("")
        self.label_imagePath.setObjectName("label_imagePath")
        self.horizontalLayout_2.addWidget(self.label_imagePath)
        self.btn_confirm_update = QtWidgets.QPushButton(parent=self.widget)
        self.btn_confirm_update.setObjectName("btn_confirm_update")
        self.horizontalLayout_2.addWidget(self.btn_confirm_update)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.widget)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(parent=CustomerManagement)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.updateButton = QtWidgets.QPushButton(parent=CustomerManagement)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout.addWidget(self.updateButton)
        self.deleteButton = QtWidgets.QPushButton(parent=CustomerManagement)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.clearButton = QtWidgets.QPushButton(parent=CustomerManagement)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.customerTableView = QtWidgets.QTableView(parent=CustomerManagement)
        self.customerTableView.setSizeIncrement(QtCore.QSize(1, 0))
        self.customerTableView.setObjectName("customerTableView")
        self.customerTableView.setStyleSheet("""
            QTableView {
                gridline-color: white;
                background-color:black;
            }
            QTableView::item {
                padding: 5px;
            }
            QTableView::item:selected {
                background-color: #d9edf7;
                color: #333;
            }
    QRadioButton {
        margin-left: 10px;
        border-radius:50%;
    }
    QRadioButton::indicator {
        width: 16px;
        height: 16px;
    }
    QHeaderView::section {
        background-color: #4CAF50;
        color: white;
        padding: 5px;
        border: none;
    }

        """)
        self.verticalLayout_3.addWidget(self.customerTableView)
        self.mainLayout.addLayout(self.verticalLayout_3)
        self.radio_group_customer = QButtonGroup(self)
        self.radio_group_customer.setExclusive(True)
        self.retranslateUi(CustomerManagement)
        QtCore.QMetaObject.connectSlotsByName(CustomerManagement)

    def retranslateUi(self, CustomerManagement):
        _translate = QtCore.QCoreApplication.translate
        CustomerManagement.setWindowTitle(_translate("CustomerManagement", "Customer Management"))
        self.searchLabel.setText(_translate("CustomerManagement", "Tìm kiếm"))
        self.searchButton.setText(_translate("CustomerManagement", "Tìm"))
        self.label_2.setText(_translate("CustomerManagement", "Họ và tên"))
        self.label_3.setText(_translate("CustomerManagement", "Số điện thoại"))
        self.label_4.setText(_translate("CustomerManagement", "Đường dẫn"))
        self.imageButton.setText(_translate("CustomerManagement", "Chọn hình"))
        self.btn_confirm_update.setText(_translate("CustomerManagement", "Xác nhận sửa"))
        self.addButton.setText(_translate("CustomerManagement", "Thêm"))
        self.updateButton.setText(_translate("CustomerManagement", "sửa"))
        self.deleteButton.setText(_translate("CustomerManagement", "xóa"))
        self.clearButton.setText(_translate("CustomerManagement", "Làm mới"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomerManagement = QtWidgets.QWidget()
    ui = Ui_CustomerManagement()
    ui.setupUi(CustomerManagement)
    CustomerManagement.show()
    sys.exit(app.exec())
