# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_bar = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 120, 540))
        self.menu_bar.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.menu_bar.setTitle("")
        self.menu_bar.setObjectName("menu_bar")
        self.btn_phong = QtWidgets.QPushButton(parent=self.menu_bar)
        self.btn_phong.setGeometry(QtCore.QRect(10, 30, 93, 51))
        self.btn_phong.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_phong.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.btn_phong.setObjectName("btn_phong")
        self.btn_gia = QtWidgets.QPushButton(parent=self.menu_bar)
        self.btn_gia.setGeometry(QtCore.QRect(10, 90, 93, 51))
        self.btn_gia.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.btn_gia.setObjectName("btn_gia")
        self.btn_taikhoan = QtWidgets.QPushButton(parent=self.menu_bar)
        self.btn_taikhoan.setGeometry(QtCore.QRect(10, 510, 93, 28))
        self.btn_taikhoan.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.btn_taikhoan.setObjectName("btn_taikhoan")
        self.btn_dichvu = QtWidgets.QPushButton(parent=self.menu_bar)
        self.btn_dichvu.setGeometry(QtCore.QRect(10, 150, 93, 51))
        self.btn_dichvu.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.btn_dichvu.setObjectName("btn_dichvu")
        self.man_hinh = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.man_hinh.setGeometry(QtCore.QRect(120, 0, 680, 540))
        self.man_hinh.setStyleSheet("")
        self.man_hinh.setObjectName("man_hinh")
        self.phong_screen = QtWidgets.QWidget()
        self.phong_screen.setObjectName("phong_screen")
        self.man_hinh.addWidget(self.phong_screen)
        self.gia_screen = QtWidgets.QWidget()
        self.gia_screen.setObjectName("gia_screen")
        self.man_hinh.addWidget(self.gia_screen)
        self.dichvu_screen = QtWidgets.QWidget()
        self.dichvu_screen.setObjectName("dichvu_screen")
        self.man_hinh.addWidget(self.dichvu_screen)
        self.taikhoan_screen = QtWidgets.QWidget()
        self.taikhoan_screen.setObjectName("taikhoan_screen")
        self.man_hinh.addWidget(self.taikhoan_screen)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.man_hinh.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_phong.setText(_translate("MainWindow", "Phòng"))
        self.btn_gia.setText(_translate("MainWindow", "Giá phòng"))
        self.btn_taikhoan.setText(_translate("MainWindow", "Tài khoản"))
        self.btn_dichvu.setText(_translate("MainWindow", "Dịch vụ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
