# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ql_nhan_vien.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 540)
        
        self.dis_pla = QtWidgets.QTableWidget(parent=Form)
        self.dis_pla.setGeometry(QtCore.QRect(40, 80, 601, 290))
        self.dis_pla.setColumnCount(6)
        self.dis_pla.setObjectName("dis_pla")
        self.dis_pla.setRowCount(0)
        
        for i, header in enumerate(["ID", "Tên", "Email", "Số điện thoại", "Địa chỉ", "Chức vụ"]):
            item = QtWidgets.QTableWidgetItem()
            self.dis_pla.setHorizontalHeaderItem(i, item)
        
        self.splitter_2 = QtWidgets.QSplitter(parent=Form)
        self.splitter_2.setGeometry(QtCore.QRect(60, 30, 231, 30))
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        
        self.label = QtWidgets.QLabel(parent=self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.in_sea = QtWidgets.QLineEdit(parent=self.splitter_2)
        self.in_sea.setFont(font)
        self.in_sea.setObjectName("in_sea")
        
        self.sea_btn = QtWidgets.QPushButton(parent=self.splitter_2)
        self.sea_btn.setFont(font)
        self.sea_btn.setObjectName("sea_btn")
        
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 380, 561, 80))
        self.layoutWidget.setObjectName("layoutWidget")
        
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        self.grid_labels = ["ID", "Tên", "Email", "Số ĐT", "Địa chỉ", "Chức Vụ"]
        self.grid_widgets = {}
        
        for i, label in enumerate(self.grid_labels):
            row, col = divmod(i, 2)
            lbl = QtWidgets.QLabel(parent=self.layoutWidget)
            lbl.setObjectName(f"label_{i+2}")
            self.gridLayout.addWidget(lbl, row, col * 2)
            
            line_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
            line_edit.setObjectName(f"in_{label.lower()}")
            self.gridLayout.addWidget(line_edit, row, col * 2 + 1)
            
            self.grid_widgets[label] = line_edit
        
        button_font = QtGui.QFont()
        button_font.setPointSize(11)
        
        self.ins_btn = QtWidgets.QPushButton(parent=Form)
        self.ins_btn.setGeometry(QtCore.QRect(40, 470, 100, 40))
        self.ins_btn.setFont(button_font)
        self.ins_btn.setObjectName("ins_btn")
        
        self.del_btn = QtWidgets.QPushButton(parent=Form)
        self.del_btn.setGeometry(QtCore.QRect(164, 470, 100, 40))
        self.del_btn.setFont(button_font)
        self.del_btn.setObjectName("del_btn")
        
        self.edi_btn = QtWidgets.QPushButton(parent=Form)
        self.edi_btn.setGeometry(QtCore.QRect(288, 470, 100, 40))
        self.edi_btn.setFont(button_font)
        self.edi_btn.setObjectName("edi_btn")
        
        self.sho_btn = QtWidgets.QPushButton(parent=Form)
        self.sho_btn.setGeometry(QtCore.QRect(412, 470, 100, 40))
        self.sho_btn.setFont(button_font)
        self.sho_btn.setObjectName("sho_btn")
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        
        for i, text in enumerate(["ID", "Tên", "Email", "Số điện thoại", "Địa chỉ", "Chức vụ"]):
            item = self.dis_pla.horizontalHeaderItem(i)
            item.setText(_translate("Form", text))
        
        self.label.setText(_translate("Form", "ID"))
        self.sea_btn.setText(_translate("Form", "Tìm kiếm"))
        
        for i, text in enumerate(["ID", "Tên", "Email", "Số ĐT", "Địa chỉ", "Chức Vụ"]):
            lbl = self.layoutWidget.findChild(QtWidgets.QLabel, f"label_{i+2}")
            if lbl:
                lbl.setText(_translate("Form", text))
        
        self.ins_btn.setText(_translate("Form", "Thêm"))
        self.edi_btn.setText(_translate("Form", "Sửa"))
        self.sho_btn.setText(_translate("Form", "Hiển thị"))
        self.del_btn.setText(_translate("Form", "Xóa"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())