# Form implementation generated from reading ui file 'tai_khoan.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 540)
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(330, 90, 291, 128))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.nv_diachi = QtWidgets.QLabel(parent=self.layoutWidget)
        self.nv_diachi.setObjectName("nv_diachi")
        self.gridLayout.addWidget(self.nv_diachi, 4, 1, 1, 1)
        self.nv_id = QtWidgets.QLabel(parent=self.layoutWidget)
        self.nv_id.setObjectName("nv_id")
        self.gridLayout.addWidget(self.nv_id, 0, 1, 1, 1)
        self.nv_sdt = QtWidgets.QLabel(parent=self.layoutWidget)
        self.nv_sdt.setObjectName("nv_sdt")
        self.gridLayout.addWidget(self.nv_sdt, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.nv_email = QtWidgets.QLabel(parent=self.layoutWidget)
        self.nv_email.setObjectName("nv_email")
        self.gridLayout.addWidget(self.nv_email, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.nv_chucvu = QtWidgets.QLabel(parent=self.layoutWidget)
        self.nv_chucvu.setObjectName("nv_chucvu")
        self.gridLayout.addWidget(self.nv_chucvu, 5, 1, 1, 1)
        self.nv_name = QtWidgets.QLabel(parent=self.layoutWidget)
        self.nv_name.setObjectName("nv_name")
        self.gridLayout.addWidget(self.nv_name, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(parent=Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 90, 261, 62))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.user_id = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.user_id.setObjectName("user_id")
        self.gridLayout_2.addWidget(self.user_id, 0, 1, 1, 1)
        self.user_name = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.user_name.setObjectName("user_name")
        self.gridLayout_2.addWidget(self.user_name, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Email"))
        self.label_8.setText(_translate("Form", "Địa chỉ"))
        self.nv_diachi.setText(_translate("Form", "***"))
        self.nv_id.setText(_translate("Form", "***"))
        self.nv_sdt.setText(_translate("Form", "***"))
        self.label_4.setText(_translate("Form", "Tên NV"))
        self.label_7.setText(_translate("Form", "Chức vụ"))
        self.nv_email.setText(_translate("Form", "***"))
        self.label_6.setText(_translate("Form", "SĐT"))
        self.nv_chucvu.setText(_translate("Form", "***"))
        self.nv_name.setText(_translate("Form", "***"))
        self.label_3.setText(_translate("Form", "Mã NV"))
        self.user_id.setText(_translate("Form", "***"))
        self.user_name.setText(_translate("Form", "***"))
        self.label_2.setText(_translate("Form", "username"))
        self.label.setText(_translate("Form", "userID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
