# Form implementation generated from reading ui file 'view\tai_khoan\tai_khoan_foradmin.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(656, 452)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.inp_sea = QtWidgets.QLineEdit(parent=Form)
        self.inp_sea.setObjectName("inp_sea")
        self.gridLayout.addWidget(self.inp_sea, 0, 1, 1, 1)
        self.sea_btn = QtWidgets.QPushButton(parent=Form)
        self.sea_btn.setObjectName("sea_btn")
        self.gridLayout.addWidget(self.sea_btn, 0, 2, 1, 1)
        self.dis_pla = QtWidgets.QTableWidget(parent=Form)
        self.dis_pla.setObjectName("dis_pla")
        self.dis_pla.setColumnCount(9)
        self.dis_pla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(8, item)
        self.gridLayout.addWidget(self.dis_pla, 1, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.them_btn = QtWidgets.QPushButton(parent=Form)
        self.them_btn.setObjectName("them_btn")
        self.horizontalLayout.addWidget(self.them_btn)
        self.xoa_btn = QtWidgets.QPushButton(parent=Form)
        self.xoa_btn.setObjectName("xoa_btn")
        self.horizontalLayout.addWidget(self.xoa_btn)
        self.sua_btn = QtWidgets.QPushButton(parent=Form)
        self.sua_btn.setObjectName("sua_btn")
        self.horizontalLayout.addWidget(self.sua_btn)
        self.hienthi_btn = QtWidgets.QPushButton(parent=Form)
        self.hienthi_btn.setObjectName("hienthi_btn")
        self.horizontalLayout.addWidget(self.hienthi_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID"))
        self.sea_btn.setText(_translate("Form", "Tìm"))
        item = self.dis_pla.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.dis_pla.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên tài khoản"))
        item = self.dis_pla.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Mật khẩu"))
        item = self.dis_pla.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Mã nhân viên"))
        item = self.dis_pla.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Họ và tên"))
        item = self.dis_pla.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Email"))
        item = self.dis_pla.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Số điện thoại"))
        item = self.dis_pla.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Địa chỉ"))
        item = self.dis_pla.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Chức vụ"))
        self.them_btn.setText(_translate("Form", "Thêm"))
        self.xoa_btn.setText(_translate("Form", "Xóa"))
        self.sua_btn.setText(_translate("Form", "Sửa"))
        self.hienthi_btn.setText(_translate("Form", "Hiển thị"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
