# Form implementation generated from reading ui file 'C:\Code\DoAnPython\view\DatPhong\dat_phong_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dat_phong(object):
    def setupUi(self, dat_phong):
        dat_phong.setObjectName("dat_phong")
        dat_phong.resize(807, 490)
        self.label = QtWidgets.QLabel(parent=dat_phong)
        self.label.setGeometry(QtCore.QRect(220, 80, 201, 91))
        self.label.setObjectName("label")

        self.retranslateUi(dat_phong)
        QtCore.QMetaObject.connectSlotsByName(dat_phong)

    def retranslateUi(self, dat_phong):
        _translate = QtCore.QCoreApplication.translate
        dat_phong.setWindowTitle(_translate("dat_phong", "Form"))
        self.label.setText(_translate("dat_phong", "Day la trang dat phong"))
