# Form implementation generated from reading ui file 'view/check_in/checkin.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QButtonGroup

class Ui_Checkin(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 686)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        Form.setStyleSheet("""
            QWidget {
                background-color: #f5f5f5;
                font-family: Arial, sans-serif;
            }
            QLabel {
                color: #333;
            }
            QLineEdit {
                border: 1px solid #ccc;
                border-radius: 5px;
                padding: 5px;
                background-color: #fff;
            }
            QPushButton {
                background-color: #007bff;
                color: #fff;
                border: none;
                border-radius: 5px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #0056b3;
            }
            QTableWidget {
                border: 1px solid #ccc;
                background-color: #fff;
            }
            QHeaderView::section {
                background-color: #007bff;
                color: #fff;
                padding: 5px;
                border: none;
            }
        """)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchbar = QtWidgets.QGridLayout()
        self.searchbar.setObjectName("searchbar")
        self.label_customer = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_customer.setFont(font)
        self.label_customer.setObjectName("label_customer")
        self.searchbar.addWidget(self.label_customer, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.searchbar.addWidget(self.label, 0, 2, 1, 1)
        self.label_room = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_room.setFont(font)
        self.label_room.setObjectName("label_room")
        self.searchbar.addWidget(self.label_room, 1, 0, 1, 1)
        self.search_room = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_room.setFont(font)
        self.search_room.setObjectName("search_room")
        self.searchbar.addWidget(self.search_room, 1, 1, 1, 1)
        self.search_customer = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_customer.setFont(font)
        self.search_customer.setObjectName("search_customer")
        self.searchbar.addWidget(self.search_customer, 0, 1, 1, 1)
        self.search_name = QtWidgets.QLineEdit(parent=Form)
        self.search_name.setObjectName("search_name")
        self.searchbar.addWidget(self.search_name, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.reset_btn = QtWidgets.QPushButton(parent=Form)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout_2.addWidget(self.reset_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.searchbar.addLayout(self.horizontalLayout_2, 1, 3, 1, 1)
        self.horizontalLayout.addLayout(self.searchbar)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.view_customer = QtWidgets.QTableWidget(parent=Form)
        self.view_customer.setObjectName("view_customer")
        self.view_customer.setColumnCount(5)
        self.view_customer.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.view_customer.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.view_customer.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.view_customer.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.view_customer.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.view_customer.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.view_customer)
        self.view_room = QtWidgets.QTableWidget(parent=Form)
        self.view_room.setObjectName("view_room")
        self.view_room.setColumnCount(6)
        self.view_room.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.view_room.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.view_room.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.view_room.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.view_room.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.view_room.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.view_room.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.view_room)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.checkin_button = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkin_button.setFont(font)
        self.checkin_button.setObjectName("checkin_button")
        self.verticalLayout_3.addWidget(self.checkin_button)
        self.radio_group = QButtonGroup(self)
        self.radio_group.setExclusive(True)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_customer.setText(_translate("Form", "id_customer"))
        self.label.setText(_translate("Form", "Họ tên"))
        self.label_room.setText(_translate("Form", "id_room"))
        self.reset_btn.setText(_translate("Form", "Khôi phục"))
        self.pushButton.setText(_translate("Form", "tìm kiếm"))
        item = self.view_customer.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Chọn"))
        item = self.view_customer.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ID"))
        item = self.view_customer.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Họ tên"))
        item = self.view_customer.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Số điện thoại"))
        item = self.view_customer.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Image"))
        item = self.view_room.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.view_room.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên phòng"))
        item = self.view_room.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Số giường "))
        item = self.view_room.horizontalHeaderItem(3)
        item.setText(_translate("Form", "ID giá"))
        item = self.view_room.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tình trạng đặt phòng"))
        item = self.view_room.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Tình trạng sử dụng"))
        self.checkin_button.setText(_translate("Form", "bắt đầu check in"))
