# Form implementation generated from reading ui file 'D:\DoAnPython\view\statistics\statistics_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StatisticsMainWindow(object):
    def setupUi(self, StatisticsMainWindow):
        StatisticsMainWindow.setObjectName("StatisticsMainWindow")
        StatisticsMainWindow.resize(854, 643)
        font = QtGui.QFont()
        font.setPointSize(11)
        StatisticsMainWindow.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=StatisticsMainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 831, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TongQuanBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.TongQuanBtn.setObjectName("TongQuanBtn")
        self.horizontalLayout.addWidget(self.TongQuanBtn)
        self.DoanThuBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.DoanThuBtn.setObjectName("DoanThuBtn")
        self.horizontalLayout.addWidget(self.DoanThuBtn)
        self.PhongBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.PhongBtn.setObjectName("PhongBtn")
        self.horizontalLayout.addWidget(self.PhongBtn)
        self.MenuBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.MenuBtn.setObjectName("MenuBtn")
        self.horizontalLayout.addWidget(self.MenuBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.verticalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(StatisticsMainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(StatisticsMainWindow)

    def retranslateUi(self, StatisticsMainWindow):
        _translate = QtCore.QCoreApplication.translate
        StatisticsMainWindow.setWindowTitle(_translate("StatisticsMainWindow", "Statistics"))
        self.TongQuanBtn.setText(_translate("StatisticsMainWindow", "Tổng Quan"))
        self.DoanThuBtn.setText(_translate("StatisticsMainWindow", "Doanh Thu"))
        self.PhongBtn.setText(_translate("StatisticsMainWindow", "Phòng"))
        self.MenuBtn.setText(_translate("StatisticsMainWindow", "Menu"))

