# Form implementation generated from reading ui file 'D:\DoAnPython\view\statistics\statistics_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StatisticsMainWindow(object):
    def setupUi(self, StatisticsMainWindow):
        StatisticsMainWindow.setObjectName("StatisticsMainWindow")
        StatisticsMainWindow.resize(854, 634)
        font = QtGui.QFont()
        font.setPointSize(11)
        StatisticsMainWindow.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(StatisticsMainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TongQuanBtn = QtWidgets.QPushButton(parent=StatisticsMainWindow)
        self.TongQuanBtn.setObjectName("TongQuanBtn")
        self.horizontalLayout.addWidget(self.TongQuanBtn)
        self.DoanThuBtn = QtWidgets.QPushButton(parent=StatisticsMainWindow)
        self.DoanThuBtn.setObjectName("DoanThuBtn")
        self.horizontalLayout.addWidget(self.DoanThuBtn)
        self.PhongBtn = QtWidgets.QPushButton(parent=StatisticsMainWindow)
        self.PhongBtn.setObjectName("PhongBtn")
        self.horizontalLayout.addWidget(self.PhongBtn)
        self.MenuBtn = QtWidgets.QPushButton(parent=StatisticsMainWindow)
        self.MenuBtn.setObjectName("MenuBtn")
        self.horizontalLayout.addWidget(self.MenuBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=StatisticsMainWindow)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(StatisticsMainWindow)
        QtCore.QMetaObject.connectSlotsByName(StatisticsMainWindow)

    def retranslateUi(self, StatisticsMainWindow):
        _translate = QtCore.QCoreApplication.translate
        StatisticsMainWindow.setWindowTitle(_translate("StatisticsMainWindow", "Statistics"))
        self.TongQuanBtn.setText(_translate("StatisticsMainWindow", "Tổng Quan"))
        self.DoanThuBtn.setText(_translate("StatisticsMainWindow", "Doanh Thu"))
        self.PhongBtn.setText(_translate("StatisticsMainWindow", "Phòng"))
        self.MenuBtn.setText(_translate("StatisticsMainWindow", "Menu"))
