# Form implementation generated from reading ui file 'D:\DoAnPython\view\statistics\statistics_ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StatisticsMainWindow(object):
    def setupUi(self, StatisticsMainWindow):
        StatisticsMainWindow.setObjectName("StatisticsMainWindow")
        StatisticsMainWindow.resize(1143, 839)
        font = QtGui.QFont()
        font.setPointSize(11)
        StatisticsMainWindow.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(StatisticsMainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.TongQuanBtn = QtWidgets.QPushButton(parent=StatisticsMainWindow)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.TongQuanBtn.setFont(font)
        self.TongQuanBtn.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;  /* Blue background */\n"
"                color: white;  /* White text */\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                font-size: 14px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9; /* Darker blue on hover */\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #1f618d; /* Even darker blue on press */\n"
"            }")
        self.TongQuanBtn.setObjectName("TongQuanBtn")
        self.horizontalLayout.addWidget(self.TongQuanBtn)
        self.DoanhThuBtn = QtWidgets.QPushButton(parent=StatisticsMainWindow)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.DoanhThuBtn.setFont(font)
        self.DoanhThuBtn.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;  /* Blue background */\n"
"                color: white;  /* White text */\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                font-size: 14px;\n"
"                border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9; /* Darker blue on hover */\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #1f618d; /* Even darker blue on press */\n"
"            }")
        self.DoanhThuBtn.setObjectName("DoanhThuBtn")
        self.horizontalLayout.addWidget(self.DoanhThuBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=StatisticsMainWindow)
        self.stackedWidget.setObjectName("stackedWidget")
        self.overViewPage = QtWidgets.QWidget()
        self.overViewPage.setObjectName("overViewPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.overViewPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(parent=self.overViewPage)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\DoAnPython\\view\\statistics\\../../image/6851200.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.occupied_rooms = QtWidgets.QLabel(parent=self.overViewPage)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.occupied_rooms.setFont(font)
        self.occupied_rooms.setStyleSheet("QLabel{\n"
"    font-weight : bold;\n"
"    font-size: 4rem;\n"
"    color:white ;\n"
"}")
        self.occupied_rooms.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.occupied_rooms.setObjectName("occupied_rooms")
        self.verticalLayout_2.addWidget(self.occupied_rooms, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(parent=self.overViewPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(parent=self.overViewPage)
        self.label_9.setMaximumSize(QtCore.QSize(100, 100))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("D:\\DoAnPython\\view\\statistics\\../../image/5734963.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.available_rooms = QtWidgets.QLabel(parent=self.overViewPage)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.available_rooms.setFont(font)
        self.available_rooms.setStyleSheet("QLabel{\n"
"    font-weight : bold;\n"
"    font-size: 4rem;\n"
"    color:white ;\n"
"}")
        self.available_rooms.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.available_rooms.setObjectName("available_rooms")
        self.verticalLayout_4.addWidget(self.available_rooms, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(parent=self.overViewPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.overViewPage)
        self.label_5.setMinimumSize(QtCore.QSize(100, 100))
        self.label_5.setMaximumSize(QtCore.QSize(130, 100))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\DoAnPython\\view\\statistics\\../../image/383-3830000_roadmap-clipart.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.staffs = QtWidgets.QLabel(parent=self.overViewPage)
        self.staffs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.staffs.setFont(font)
        self.staffs.setStyleSheet("QLabel{\n"
"    font-weight : bold;\n"
"    font-size: 4rem;\n"
"    color:white ;\n"
"}")
        self.staffs.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.staffs.setObjectName("staffs")
        self.verticalLayout_3.addWidget(self.staffs, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(parent=self.overViewPage)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.overview_screen = QtWidgets.QVBoxLayout()
        self.overview_screen.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.overview_screen.setContentsMargins(-1, 10, -1, 0)
        self.overview_screen.setSpacing(15)
        self.overview_screen.setObjectName("overview_screen")
        self.verticalLayout_5.addLayout(self.overview_screen)
        self.tableOverView = QtWidgets.QTableView(parent=self.overViewPage)
        self.tableOverView.setMinimumSize(QtCore.QSize(1085, 250))
        self.tableOverView.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tableOverView.setBaseSize(QtCore.QSize(1085, 250))
        self.tableOverView.setStyleSheet("QTableView {\n"
"        font-size: 14px;\n"
"        }")
        self.tableOverView.setObjectName("tableOverView")
        self.verticalLayout_5.addWidget(self.tableOverView)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.stackedWidget.addWidget(self.overViewPage)
        self.doanhThuPage = QtWidgets.QWidget()
        self.doanhThuPage.setObjectName("doanhThuPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.doanhThuPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.StaYearBtn = QtWidgets.QPushButton(parent=self.doanhThuPage)
        self.StaYearBtn.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;  /* Blue background */\n"
"                color: white;  /* White text */\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                font-size: 14px;\n"
"                \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9; /* Darker blue on hover */\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #1f618d; /* Even darker blue on press */\n"
"            }")
        self.StaYearBtn.setObjectName("StaYearBtn")
        self.horizontalLayout_6.addWidget(self.StaYearBtn)
        self.StaMonthBtn = QtWidgets.QPushButton(parent=self.doanhThuPage)
        self.StaMonthBtn.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;  /* Blue background */\n"
"                color: white;  /* White text */\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                font-size: 14px;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9; /* Darker blue on hover */\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #1f618d; /* Even darker blue on press */\n"
"            }")
        self.StaMonthBtn.setObjectName("StaMonthBtn")
        self.horizontalLayout_6.addWidget(self.StaMonthBtn)
        self.StaDayToDayBtn = QtWidgets.QPushButton(parent=self.doanhThuPage)
        self.StaDayToDayBtn.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;  /* Blue background */\n"
"                color: white;  /* White text */\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                font-size: 14px;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9; /* Darker blue on hover */\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #1f618d; /* Even darker blue on press */\n"
"            }")
        self.StaDayToDayBtn.setObjectName("StaDayToDayBtn")
        self.horizontalLayout_6.addWidget(self.StaDayToDayBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.doanhThuPage)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.thongKeTheoNamPage = QtWidgets.QWidget()
        self.thongKeTheoNamPage.setObjectName("thongKeTheoNamPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.thongKeTheoNamPage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.label_3 = QtWidgets.QLabel(parent=self.thongKeTheoNamPage)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.startYearTXT = QtWidgets.QLineEdit(parent=self.thongKeTheoNamPage)
        self.startYearTXT.setMinimumSize(QtCore.QSize(0, 0))
        self.startYearTXT.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.startYearTXT.setFont(font)
        self.startYearTXT.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.startYearTXT.setStyleSheet("            QLineEdit:hover {\n"
"                border: 2px solid #2980b9; /* Darker blue on hover */\n"
"            }\n"
"            ")
        self.startYearTXT.setObjectName("startYearTXT")
        self.horizontalLayout_7.addWidget(self.startYearTXT)
        self.label_4 = QtWidgets.QLabel(parent=self.thongKeTheoNamPage)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.endYearTXT = QtWidgets.QLineEdit(parent=self.thongKeTheoNamPage)
        self.endYearTXT.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.endYearTXT.setFont(font)
        self.endYearTXT.setStyleSheet("QLineEdit:hover {\n"
"                border: 2px solid #2980b9; /* Darker blue on hover */\n"
"            }")
        self.endYearTXT.setObjectName("endYearTXT")
        self.horizontalLayout_7.addWidget(self.endYearTXT)
        self.statistisBtn = QtWidgets.QPushButton(parent=self.thongKeTheoNamPage)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.statistisBtn.setFont(font)
        self.statistisBtn.setStyleSheet("QPushButton {\n"
"                background-color: #f5f5f5; \n"
"                color: black;\n"
"                border: none;\n"
"                padding: 5px 5px;\n"
"                font-size: 14px;\n"
"                border-radius : 5px;\n"
"                font-weight: bold;\n"
"            }\n"
"QPushButton:hover {\n"
"               border: 1px solid #2980b9;\n"
"               background-color: white; \n"
"}\n"
"QPushButton:pressed {\n"
"               background-color: white; \n"
"}")
        self.statistisBtn.setObjectName("statistisBtn")
        self.horizontalLayout_7.addWidget(self.statistisBtn)
        self.refreshBtn = QtWidgets.QPushButton(parent=self.thongKeTheoNamPage)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.refreshBtn.setFont(font)
        self.refreshBtn.setStyleSheet("QPushButton {\n"
"                background-color: #f5f5f5; \n"
"                color: black;\n"
"                border: none;\n"
"                padding: 5px 5px;\n"
"                font-size: 14px;\n"
"                border-radius : 5px;\n"
"                font-weight: bold;\n"
"            }\n"
"QPushButton:hover {\n"
"               border: 1px solid #2980b9;\n"
"               background-color: white; \n"
"}\n"
"QPushButton:pressed {\n"
"               background-color: white; \n"
"}")
        self.refreshBtn.setObjectName("refreshBtn")
        self.horizontalLayout_7.addWidget(self.refreshBtn)
        self.exportExcelBtn = QtWidgets.QPushButton(parent=self.thongKeTheoNamPage)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.exportExcelBtn.setFont(font)
        self.exportExcelBtn.setStyleSheet("QPushButton {\n"
"                background-color: #f5f5f5; \n"
"                color: black;\n"
"                border: none;\n"
"                padding: 5px 5px;\n"
"                font-size: 14px;\n"
"                border-radius : 5px;\n"
"                font-weight: bold;\n"
"            }\n"
"QPushButton:hover {\n"
"               border: 1px solid #2980b9;\n"
"               background-color: white; \n"
"}\n"
"QPushButton:pressed {\n"
"               background-color: white; \n"
"}")
        self.exportExcelBtn.setObjectName("exportExcelBtn")
        self.horizontalLayout_7.addWidget(self.exportExcelBtn)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem10)
        self.yearScreenChart = QtWidgets.QVBoxLayout()
        self.yearScreenChart.setObjectName("yearScreenChart")
        self.verticalLayout_10.addLayout(self.yearScreenChart)
        self.tableYearStatisticView = QtWidgets.QTableView(parent=self.thongKeTheoNamPage)
        self.tableYearStatisticView.setMinimumSize(QtCore.QSize(1077, 250))
        self.tableYearStatisticView.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tableYearStatisticView.setStyleSheet("QTableView {\n"
"        font-size: 14px;\n"
"        }\n"
"   ")
        self.tableYearStatisticView.setObjectName("tableYearStatisticView")
        self.verticalLayout_10.addWidget(self.tableYearStatisticView)
        self.stackedWidget_2.addWidget(self.thongKeTheoNamPage)
        self.thongKeTheoTNTTPage = QtWidgets.QWidget()
        self.thongKeTheoTNTTPage.setObjectName("thongKeTheoTNTTPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.thongKeTheoTNTTPage)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(parent=self.thongKeTheoTNTTPage)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.yearOfMonths = QtWidgets.QSpinBox(parent=self.thongKeTheoTNTTPage)
        self.yearOfMonths.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.yearOfMonths.setSuffix("")
        self.yearOfMonths.setMinimum(0)
        self.yearOfMonths.setMaximum(10000)
        self.yearOfMonths.setObjectName("yearOfMonths")
        self.horizontalLayout_8.addWidget(self.yearOfMonths)
        self.exportExcelBtn_2 = QtWidgets.QPushButton(parent=self.thongKeTheoTNTTPage)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.exportExcelBtn_2.setFont(font)
        self.exportExcelBtn_2.setStyleSheet("QPushButton {\n"
"                background-color: #f5f5f5; \n"
"                color: black;\n"
"                border: none;\n"
"                padding: 5px 5px;\n"
"                font-size: 14px;\n"
"                border-radius : 5px;\n"
"                font-weight: bold;\n"
"            }\n"
"QPushButton:hover {\n"
"               border: 1px solid #2980b9;\n"
"               background-color: white; \n"
"}\n"
"QPushButton:pressed {\n"
"               background-color: white; \n"
"}")
        self.exportExcelBtn_2.setObjectName("exportExcelBtn_2")
        self.horizontalLayout_8.addWidget(self.exportExcelBtn_2, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem11)
        self.monthScreenChart = QtWidgets.QVBoxLayout()
        self.monthScreenChart.setObjectName("monthScreenChart")
        self.verticalLayout_12.addLayout(self.monthScreenChart)
        self.tableMonthStatisticView = QtWidgets.QTableView(parent=self.thongKeTheoTNTTPage)
        self.tableMonthStatisticView.setMinimumSize(QtCore.QSize(1077, 250))
        self.tableMonthStatisticView.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tableMonthStatisticView.setStyleSheet("QTableView {\n"
"        font-size: 14px;\n"
"        }\n"
"   ")
        self.tableMonthStatisticView.setObjectName("tableMonthStatisticView")
        self.verticalLayout_12.addWidget(self.tableMonthStatisticView)
        self.stackedWidget_2.addWidget(self.thongKeTheoTNTTPage)
        self.thongKeTheoTTTNPage = QtWidgets.QWidget()
        self.thongKeTheoTTTNPage.setObjectName("thongKeTheoTTTNPage")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.thongKeTheoTTTNPage)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.label_10 = QtWidgets.QLabel(parent=self.thongKeTheoTTTNPage)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.dateStartTXT = QtWidgets.QDateEdit(parent=self.thongKeTheoTTTNPage)
        self.dateStartTXT.setObjectName("dateStartTXT")
        self.horizontalLayout_9.addWidget(self.dateStartTXT)
        self.label_11 = QtWidgets.QLabel(parent=self.thongKeTheoTTTNPage)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.dateEndTXT = QtWidgets.QDateEdit(parent=self.thongKeTheoTTTNPage)
        self.dateEndTXT.setObjectName("dateEndTXT")
        self.horizontalLayout_9.addWidget(self.dateEndTXT)
        self.statisticDateBtn = QtWidgets.QPushButton(parent=self.thongKeTheoTTTNPage)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.statisticDateBtn.setFont(font)
        self.statisticDateBtn.setStyleSheet("QPushButton {\n"
"                background-color: #f5f5f5; \n"
"                color: black;\n"
"                border: none;\n"
"                padding: 5px 5px;\n"
"                font-size: 14px;\n"
"                border-radius : 5px;\n"
"                font-weight: bold;\n"
"            }\n"
"QPushButton:hover {\n"
"               border: 1px solid #2980b9;\n"
"               background-color: white; \n"
"}\n"
"QPushButton:pressed {\n"
"               background-color: white; \n"
"}")
        self.statisticDateBtn.setObjectName("statisticDateBtn")
        self.horizontalLayout_9.addWidget(self.statisticDateBtn)
        self.refreshDateBtn = QtWidgets.QPushButton(parent=self.thongKeTheoTTTNPage)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.refreshDateBtn.setFont(font)
        self.refreshDateBtn.setStyleSheet("QPushButton {\n"
"                background-color: #f5f5f5; \n"
"                color: black;\n"
"                border: none;\n"
"                padding: 5px 5px;\n"
"                font-size: 14px;\n"
"                border-radius : 5px;\n"
"                font-weight: bold;\n"
"            }\n"
"QPushButton:hover {\n"
"               border: 1px solid #2980b9;\n"
"               background-color: white; \n"
"}\n"
"QPushButton:pressed {\n"
"               background-color: white; \n"
"}")
        self.refreshDateBtn.setObjectName("refreshDateBtn")
        self.horizontalLayout_9.addWidget(self.refreshDateBtn)
        self.exportExcelBtn_3 = QtWidgets.QPushButton(parent=self.thongKeTheoTTTNPage)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.exportExcelBtn_3.setFont(font)
        self.exportExcelBtn_3.setStyleSheet("QPushButton {\n"
"                background-color: #f5f5f5; \n"
"                color: black;\n"
"                border: none;\n"
"                padding: 5px 5px;\n"
"                font-size: 14px;\n"
"                border-radius : 5px;\n"
"                font-weight: bold;\n"
"            }\n"
"QPushButton:hover {\n"
"               border: 1px solid #2980b9;\n"
"               background-color: white; \n"
"}\n"
"QPushButton:pressed {\n"
"               background-color: white; \n"
"}")
        self.exportExcelBtn_3.setObjectName("exportExcelBtn_3")
        self.horizontalLayout_9.addWidget(self.exportExcelBtn_3)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.tableDateStatisticView = QtWidgets.QTableView(parent=self.thongKeTheoTTTNPage)
        self.tableDateStatisticView.setStyleSheet("QTableView {\n"
"        font-size: 14px;\n"
"        }\n"
"   ")
        self.tableDateStatisticView.setObjectName("tableDateStatisticView")
        self.verticalLayout_14.addWidget(self.tableDateStatisticView)
        self.stackedWidget_2.addWidget(self.thongKeTheoTTTNPage)
        self.thongKeDayToDayPage = QtWidgets.QWidget()
        self.thongKeDayToDayPage.setObjectName("thongKeDayToDayPage")
        self.stackedWidget_2.addWidget(self.thongKeDayToDayPage)
        self.verticalLayout_7.addWidget(self.stackedWidget_2)
        self.stackedWidget.addWidget(self.doanhThuPage)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(StatisticsMainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StatisticsMainWindow)

    def retranslateUi(self, StatisticsMainWindow):
        _translate = QtCore.QCoreApplication.translate
        StatisticsMainWindow.setWindowTitle(_translate("StatisticsMainWindow", "Statistics"))
        self.TongQuanBtn.setText(_translate("StatisticsMainWindow", "Tổng Quan"))
        self.DoanhThuBtn.setText(_translate("StatisticsMainWindow", "Doanh Thu"))
        self.occupied_rooms.setText(_translate("StatisticsMainWindow", "10"))
        self.label_2.setText(_translate("StatisticsMainWindow", "PHÒNG BẬN"))
        self.available_rooms.setText(_translate("StatisticsMainWindow", "20"))
        self.label_8.setText(_translate("StatisticsMainWindow", "PHÒNG TRỐNG"))
        self.staffs.setText(_translate("StatisticsMainWindow", "10"))
        self.label_6.setText(_translate("StatisticsMainWindow", "NHÂN VIÊN"))
        self.StaYearBtn.setText(_translate("StatisticsMainWindow", "Thống Kê Theo Năm"))
        self.StaMonthBtn.setText(_translate("StatisticsMainWindow", "Thống Kê Theo Từng Tháng Trong Năm"))
        self.StaDayToDayBtn.setText(_translate("StatisticsMainWindow", "Thống Kê Từ Ngày Đến Ngày"))
        self.label_3.setText(_translate("StatisticsMainWindow", "Từ năm"))
        self.label_4.setText(_translate("StatisticsMainWindow", "Đến năm"))
        self.statistisBtn.setText(_translate("StatisticsMainWindow", "Thống Kê"))
        self.refreshBtn.setText(_translate("StatisticsMainWindow", "Làm Mới"))
        self.exportExcelBtn.setText(_translate("StatisticsMainWindow", "Xuất excel"))
        self.label_7.setText(_translate("StatisticsMainWindow", "Chọn năm thống kê"))
        self.exportExcelBtn_2.setText(_translate("StatisticsMainWindow", "Xuất excel"))
        self.label_10.setText(_translate("StatisticsMainWindow", "Từ Ngày"))
        self.label_11.setText(_translate("StatisticsMainWindow", "Đến ngày"))
        self.statisticDateBtn.setText(_translate("StatisticsMainWindow", "Thống kê"))
        self.refreshDateBtn.setText(_translate("StatisticsMainWindow", "Làm mới"))
        self.exportExcelBtn_3.setText(_translate("StatisticsMainWindow", "Xuất excel"))
