# Form implementation generated from reading ui file 'view/datphong2/datphong2.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
project_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../"))
sys.path.append(project_path)
print(project_path)
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QButtonGroup
from view.style_css import stylecss

class Ui_datphong2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(908, 736)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_2s = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2s.setObjectName("horizontalLayout_2")
        self.horizontalLayouts = QtWidgets.QHBoxLayout()
        self.horizontalLayouts.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayouts.addItem(spacerItem)
        self.khachhang_btn = QtWidgets.QPushButton(parent=Form)
        self.khachhang_btn.setObjectName("khachhang_btn")
        self.horizontalLayouts.addWidget(self.khachhang_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayouts.addItem(spacerItem1)
        self.phong_btn = QtWidgets.QPushButton(parent=Form)
        self.phong_btn.setObjectName("phong_btn")
        self.horizontalLayouts.addWidget(self.phong_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayouts.addItem(spacerItem2)
        self.horizontalLayout_2s.addLayout(self.horizontalLayouts)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2s)
        self.layoutcustomer = QtWidgets.QVBoxLayout()
        self.layoutcustomer.setObjectName("layoutcustomer")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.id_khachhang = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.id_khachhang.setFont(font)
        self.id_khachhang.setObjectName("id_khachhang")
        self.verticalLayout_6.addWidget(self.id_khachhang)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.name_khachhang = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_khachhang.setFont(font)
        self.name_khachhang.setObjectName("name_khachhang")
        self.verticalLayout_7.addWidget(self.name_khachhang)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.phone_khachhang = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_khachhang.setFont(font)
        self.phone_khachhang.setObjectName("phone_khachhang")
        self.verticalLayout_8.addWidget(self.phone_khachhang)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.btn_khachhang = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_khachhang.setFont(font)
        self.btn_khachhang.setObjectName("btn_khachhang")
        self.horizontalLayout_7.addWidget(self.btn_khachhang)
        self.layoutcustomer.addLayout(self.horizontalLayout_7)
        self.tableviewcustomer = QtWidgets.QTableWidget(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableviewcustomer.setFont(font)
        self.tableviewcustomer.setObjectName("tableviewcustomer")
        self.tableviewcustomer.setColumnCount(3)
        self.tableviewcustomer.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableviewcustomer.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableviewcustomer.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableviewcustomer.setHorizontalHeaderItem(2, item)
        self.layoutcustomer.addWidget(self.tableviewcustomer)
        
        self.verticalLayout_12.addLayout(self.layoutcustomer)
        self.layoutoom = QtWidgets.QVBoxLayout()
        self.layoutoom.setObjectName("layoutoom")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.id_phong = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.id_phong.setFont(font)
        self.id_phong.setObjectName("id_phong")
        self.verticalLayout_9.addWidget(self.id_phong)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.ten_phong = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ten_phong.setFont(font)
        self.ten_phong.setObjectName("ten_phong")
        self.verticalLayout_10.addWidget(self.ten_phong)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.btn_phong = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_phong.setFont(font)
        self.btn_phong.setObjectName("btn_phong")
        self.horizontalLayout_8.addWidget(self.btn_phong)
        self.layoutoom.addLayout(self.horizontalLayout_8)
        self.tableviewroom = QtWidgets.QTableWidget(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableviewroom.setFont(font)
        self.tableviewroom.setObjectName("tableviewroom")
        self.tableviewroom.setColumnCount(6)
        self.tableviewroom.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableviewroom.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableviewroom.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableviewroom.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableviewroom.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableviewroom.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableviewroom.setHorizontalHeaderItem(5, item)
        self.layoutoom.addWidget(self.tableviewroom)
        self.verticalLayout_12.addLayout(self.layoutoom)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.show_khachhang = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_khachhang.setStyleSheet("""
            QLabel{
                border: 5px green solid;
                color:white;
                background: #394039;
                padding:3px;}
        """)
        self.show_khachhang.setFont(font)
        self.show_khachhang.setObjectName("show_khachhang")
        self.horizontalLayout_6.addWidget(self.show_khachhang)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.show_phong = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_phong.setFont(font)
        self.show_phong.setObjectName("show_phong")
        self.horizontalLayout_6.addWidget(self.show_phong)
        self.show_phong.setStyleSheet("""
            QLabel{
                border: 5px green solid;
                color:white;
                background: #394039;
                padding:3px;}
        """)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.start_date = QtWidgets.QDateTimeEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_date.setFont(font)
        self.start_date.setObjectName("start_date")
        self.horizontalLayout.addWidget(self.start_date)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.end_date = QtWidgets.QDateTimeEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.end_date.setFont(font)
        self.end_date.setObjectName("end_date")
        self.horizontalLayout_2.addWidget(self.end_date)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tienuoctinh = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tienuoctinh.setFont(font)
        self.tienuoctinh.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tienuoctinh.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferUppercase|QtCore.Qt.InputMethodHint.ImhTime)
        self.tienuoctinh.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tienuoctinh.setObjectName("tienuoctinh")
        self.verticalLayout_3.addWidget(self.tienuoctinh)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.tienlucdat = QtWidgets.QLabel(parent=Form)
        self.tienlucdat.setObjectName("tienlucdat")
        self.horizontalLayout_5.addWidget(self.tienlucdat)
        self.listView = QtWidgets.QListView(parent=Form)
        
        self.listView.setStyleSheet("""
                QListView {
        background-color: black;
        border: 1px solid #dee2e6;
        border-radius: 8px;
        padding: 0;
        outline: none;
        font-family: 'Segoe UI', Arial;
    }
    
    QListView::item {
        background-color: #3d3d3d;
        border: 1px solid #e0e0e0;
        border-radius: 6px;
        padding: 10px 15px;
        margin: 3px;
    }
    
    QListView::item:hover {
        background-color: #e9f5ff;
        border: 1px solid #cce0ff;
        color:black;
    }
    
    
    
    QScrollBar:vertical {
        border: none;
        background: #f1f1f1;
        width: 10px;
        margin: 0px;
    }
    
    
                                    }
            """)
        self.listView.setObjectName("listView")
        self.horizontalLayout_5.addWidget(self.listView)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.note = QtWidgets.QPlainTextEdit(parent=Form)
        font = QtGui.QFont()
        
        font.setPointSize(10)
        self.note.setFont(font)
        self.note.setPlainText("")
        self.note.setObjectName("note")
        self.verticalLayout_4.addWidget(self.note)
        self.btn_submit = QtWidgets.QPushButton(parent=Form)
        self.verticalLayout_4.addWidget(self.btn_submit)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_12.addLayout(self.verticalLayout_5)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.radio_group_customer = QButtonGroup(self)
        self.radio_group_customer.setExclusive(True)
        self.radio_group_room = QButtonGroup(self)
        self.radio_group_room.setExclusive(True)
        # Thêm style cho các nút chuyển trang
        self.khachhang_btn.setStyleSheet("""
            QPushButton {
                padding: 8px 16px;
                border-radius: 4px;
                font-weight: bold;
                                         background-color:#4f4a4f;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
        """)
        
        self.phong_btn.setStyleSheet("""
            QPushButton {
                padding: 8px 16px;
                border-radius: 4px;
                font-weight: bold;
                background-color:#4f4a4f;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
        """)
            # Thêm các kết nối signal cho nút chuyển trang
        
        # Ẩn layout phòng ban đầu
        self.tableviewroom.hide()
        self.btn_phong.hide()
        self.id_phong.hide()
        self.ten_phong.hide()
        self.label_15.hide()
        self.label_16.hide()
        default_style = stylecss(Form)
        default_style.set_default()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_12.setText(_translate("Form", "ID khách hàng:"))
        self.label_13.setText(_translate("Form", "Tên Khách hàng:"))
        self.label_14.setText(_translate("Form", "SĐT:"))
        self.btn_khachhang.setText(_translate("Form", "Tìm"))
        item = self.tableviewcustomer.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableviewcustomer.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên"))
        item = self.tableviewcustomer.horizontalHeaderItem(2)
        item.setText(_translate("Form", "SĐT"))
        self.label_15.setText(_translate("Form", "ID Phòng:"))
        self.label_16.setText(_translate("Form", "Tên Phòng:"))
        self.btn_phong.setText(_translate("Form", "Tìm phòng"))
        self.btn_submit.setText(_translate("Form", "xác nhận đặt phòng"))
        self.khachhang_btn.setText(_translate("Form", "Khách Hàng"))
        self.phong_btn.setText(_translate("Form", "Phòng"))

        item = self.tableviewroom.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableviewroom.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên Phòng"))
        item = self.tableviewroom.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Số Giường"))
        item = self.tableviewroom.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Giá phòng"))
        item = self.tableviewroom.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tình trạng phòng"))
        item = self.tableviewroom.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Tình Trạng SD"))
        self.label_2.setText(_translate("Form", "khách hàng: "))
        self.show_khachhang.setText(_translate("Form", "Chưa chọn"))
        self.label_9.setText(_translate("Form", "Phòng: "))
        self.show_phong.setText(_translate("Form", "Chưa chọn"))
        self.label_3.setText(_translate("Form", "Ngày bắt đầu:"))
        self.label_4.setText(_translate("Form", "Ngày kết thúc"))
        self.label_5.setText(_translate("Form", "phí đặt cọc: "))
        self.comboBox.setItemText(0, _translate("Form", "10%"))
        self.comboBox.setItemText(1, _translate("Form", "20%"))
        self.comboBox.setItemText(2, _translate("Form", "30%"))
        self.comboBox.setItemText(3, _translate("Form", "40%"))
        self.comboBox.setItemText(4, _translate("Form", "50%"))
        self.comboBox.setItemText(5, _translate("Form", "60%"))
        self.comboBox.setItemText(6, _translate("Form", "75%"))
        self.comboBox.setItemText(7, _translate("Form", "100%"))
        self.tienuoctinh.setText(_translate("Form", "0 Đ"))
        self.label_7.setText(_translate("Form", "Tiền lúc đặt: "))
        self.tienlucdat.setText(_translate("Form", "0 Đ"))
        self.label_8.setText(_translate("Form", "Note: "))
        self.set_default()
        self.listView.show()
    def set_default(self):
        data = [f"Ngày: {0} x {0}Đ",
                f"Đêm: {0} x {0}Đ", 
                f"Giờ: {0} x {0}Đ"]
        model = QtCore.QStringListModel(data)
        self.listView.setModel(model)