# Form implementation generated from reading ui file 'view\hoadon\chitiet_hoadon.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 330)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dis_pla = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.dis_pla.setObjectName("dis_pla")
        self.dis_pla.setColumnCount(5)
        self.dis_pla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(4, item)
        self.horizontalLayout.addWidget(self.dis_pla)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.dis_pla.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã hóa đơn"))
        item = self.dis_pla.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mã dịch vụ"))
        item = self.dis_pla.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Số lượng"))
        item = self.dis_pla.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Giá lúc đặt"))
        item = self.dis_pla.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tổng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
