# Form implementation generated from reading ui file 'view\hoadon\hoadon.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(763, 598)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.inp_sea = QtWidgets.QLineEdit(parent=Form)
        self.inp_sea.setObjectName("inp_sea")
        self.horizontalLayout.addWidget(self.inp_sea)
        self.sea_btn = QtWidgets.QPushButton(parent=Form)
        self.sea_btn.setObjectName("sea_btn")
        self.horizontalLayout.addWidget(self.sea_btn)
        self.all_btn = QtWidgets.QPushButton(parent=Form)
        self.all_btn.setObjectName("all_btn")
        self.horizontalLayout.addWidget(self.all_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.dis_pla = QtWidgets.QTableWidget(parent=Form)
        self.dis_pla.setEnabled(True)
        self.dis_pla.setObjectName("dis_pla")
        self.dis_pla.setColumnCount(6)
        self.dis_pla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dis_pla.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.dis_pla)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Ngày"))
        self.sea_btn.setText(_translate("Form", "Tìm"))
        self.all_btn.setText(_translate("Form", "Tất cả hóa đơn"))
        item = self.dis_pla.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mã hóa đơn"))
        item = self.dis_pla.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tổng tiền"))
        item = self.dis_pla.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Thời gian"))
        item = self.dis_pla.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Mã nhân viên"))
        item = self.dis_pla.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tình trạng thanh toán"))
        item = self.dis_pla.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Xem chi tiết"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
